### PR TITLE
Added edit_settings command

### PR DESCRIPTION
**Pull request by CromFr**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Please use the [`.. versionadded::` directive](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).

**Comment by CromFr** [comment]
Not sure how to use it though, I did not find any example in this repo

**Comment by FichteFoll** [comment]
Correct, we haven't used it yet, but intend to do more so in the future. You'll be the one to officially introduce it :+1:

**Comment by CromFr** [comment]
I'm so proud of it :)

**Pull request merged**
