### PR TITLE
Documented INHIBIT_EXPLICIT_COMPLETIONS.

### PR DESCRIPTION
**Pull request by moltob**

### CODE REVIEW

**Comment by FichteFoll** [comment]
How about snippets?

**Comment by moltob** [comment]
I am not sure I understand your request. I simply documented one of two literals, where before it said "What does this do". Which detail of my change would require a new code snippet?

On top of this, there _is_ documentation on how to return the bitfield, just a few lines up.

**Comment by FichteFoll** [comment]
It's okay, I'll verify it myself.

**Comment by FichteFoll** [comment]
Closing in favor of #190.

**Pull request closed without merging**
