### PR TITLE
Fix title, move backers' list

### PR DESCRIPTION
**Pull request by guillermooo**

### CODE REVIEW

**Comment by guillermooo** [comment]
@FichteFoll PTAL. I can't really think of any other solution.

**Comment by FichteFoll** [comment]
What about this:

```
Sublime Text Unofficial Documentation
=====================================

Backers 2014
------------

`Backers 2014 <_static/backers_2014/backers_2014.html>`_


Index
-----

.. toctree::
```

Works for me locally.

**Comment by guillermooo** [comment]
I'll try that again. But then the link to the backers' list will only be visible in the TOC page, not in the rhs-index. Is that ok?

**Comment by FichteFoll** [comment]
Well, it's visible when you open https://docs.sublimetext.info. If we want it visible on every page then adding it to the toc is probably the easiest way. The only problem I have with it is that it requires an additional layer (the .rst) until the backers are visible but if we had more backers than right now with just from the fundraiser we would have a place to add them to.

**Comment by guillermooo** [comment]
The TOC is one of the most heavily-visited pages, so I think it's fine. I'll try to fix the title.

**Comment by FichteFoll** [comment]
Another thing that I came up with:

The title of our main page does not need to contain "Sublime Text Unofficial Documentation" because that is already added to every title anyway. Instead, it should more look like this:

```
=====
Index
=====

Backers 2014
------------

`Backers 2014 <_static/backers_2014/backers_2014.html>`_


Table of Contents
-----------------

.. toctree::
```

**Comment by guillermooo** [comment]
It isn't really and index, so used something a bit different.

**Comment by FichteFoll** [comment]
That works.

**Pull request merged**
