### PR TITLE
note about selections with preceding and following text contexts

### PR DESCRIPTION
**Pull request by keith-hall**
small tweak to keybinding context docs as discussed on Discord

### CODE REVIEW

**Comment by FichteFoll** [comment]
I think we  @can shorten this description like this:

```
Restricts the test
to the text following/preceding the caret
and the selected text.
```

Your suggestion is more precise but in the end doesn't provide any more useful information.

PS: em(/n?)-dashes are created with `--`.

**Comment by FichteFoll** [comment]
Actually, I'm not exactly happy with the entire phrasing of this. How about this (or similar):

```
``following_text``
   Test against the selected text
   and the text following that selection on a line.
```

This raises the question how this behaves with multi-line selections…

**Comment by keith-hall** [comment]
See what you think of the wording I just pushed :)

**Comment by FichteFoll** [comment]
superb 👍

**Pull request merged**
