### PR TITLE
Install: clarify that dev and nightly are for Sublime Text 2

### PR DESCRIPTION
**Pull request by nathany**
Or maybe ST2 links should be removed entirely?

### CODE REVIEW

**Comment by guillermooo** [comment]
I think we need to update this for ST3 only. I any case, it needs further revising, so I'll hold on merging this one for now. Thanks for pointing this out!

**Comment by FichteFoll** [comment]
Imo ST still has 3 channels, stable, beta and dev. The latest stable is ST 2.0.1 - 2220 (http://www.sublimetext.com/2), the latest beta is 3065 (http://www.sublimetext.com/3) and the latest dev is 3064 (http://www.sublimetext.com/3dev). I don't think it makes any sense to include links to the old ST2 channels since ST2 very likely won't receive any updates anymore and development has moved to ST3.

**Comment by FichteFoll** [comment]
Generally I think we should target our docs at ST3 (since it's the future) and note differences with ST2 somewhere, preferrably in a sidebar box. For the page we are talking about, we should mention that there. (Actually, I think I could rewrite that almost entirely.)

**Comment by nathany** [comment]
Alright. I'm going to close this PR and let you two take care of it. :-)

**Pull request closed without merging**
