### PR TITLE
The "name" attribute seems to be essential in project build systems

### PR DESCRIPTION
**Pull request by bgeron**

### CODE REVIEW

**Comment by FichteFoll** [comment]
Could you perhaps reiterate that they are required in project-specific build systems (I thought we mentioned that already) and use semantic linefeeds?

**Comment by FichteFoll** [comment]
Thanks.

**Comment by bgeron** [comment]
> Could you perhaps reiterate that they are required in project-specific build systems

Done.

> use semantic linefeeds

I added it in one place, but in the first line it would break the RST parsing, at least as previewed by GitHub.

**Comment by bgeron** [comment]
@FichteFoll I added one more commit https://github.com/bgeron/sublime-undocs/commit/8866e0161fe933f65c06db3210fc993c18197e23 on my branch, up to you if you want to merge it or just leave it as is :)

**Comment by FichteFoll** [comment]
Yeah the first line would break parsing of definition lists.

Merging the commit would be more effort than just doing a quick pass on the file later, so I'll just leave it for now.
It needs work anyway (it's outdated).

**Comment by bgeron** [comment]
Cool. Deleting my branch. Thanks!

**Pull request merged**
