### PR TITLE
Disambiguate moving to beginning of line.

### PR DESCRIPTION
**Pull request by peterkagey**
On my machine (Sublime Text 3, macOS 10.12.3) `^ + A` and `⌘ + Left` have slightly different behaviors.

- `^ + A` goes Column 1 (the beginning of the line).

- `⌘ + Left` goes to the first non-whitespace character to the left of the cursor. For example if `•` is a space and `|` is the cursor position, then:
  - `••x•y|z` becomes `••|x•yz`.
  - `••|x•yz` becomes `|••x•yz`.

This might be better described as, "Move to the first non-whitespace character to the left of the cursor, or the beginning of the line if all characters to the left of the cursor are whitespace", but I was trying for something pithier.

### CODE REVIEW

**Comment by FichteFoll** [comment]
Unfortunatly, I can't seem to find a binding for `^+A` in `Default/Default (OSX).sublime-keymap`, which is surprising to me since it has been listed in this doc page. Maybe it has been removed in ST3?

@peterokagey, can you confirm this behavior with all packages disabled?

@OdatNurd, can you confirm this behavior? (I just know that you're using OSX. 😉 )

**Comment by peterkagey** [comment]
Ah! `^+A` may just be a macOS default then.

@FichteFoll, I've confirmed that the behavior is the same even after disabling all packages and commenting out custom key bindings and preferences.

**Comment by OdatNurd** [comment]
Indeed, I can confirm this on MacOS 10.10.5 with nothing but the default packages enabled. 

As far as I'm aware, this is one of the default key bindings that the OS provides, which seems to be borne out by this list from the Apple support site: https://support.apple.com/en-ca/HT201236

Surprisingly (to me) even though the key is seemingly handled by the OS, Sublime still sees it as a key when input logging is turned on. In fact it appear to be logged twice for every key press. Possibly Sublime has some platform specific internals to provide a consistent experience across platforms or something?

**Comment by FichteFoll** [comment]
Interesting. I'll merge this for now, since it's obviously better than what we have currently. I honestly never used these  cheat sheets so I have no idea how details we should be with them, but we'll revisit them at some point anyway.

**Pull request merged**
